#! /usr/bin/env python
# encoding: utf-8

# =========== JUTILS =========== #

bld.stlib(
    features='cxx',
    source=bld.path.ant_glob('jutils/**/*.cpp'),
    target='jutils',
    lib=['android'],
    use=[],
    export_includes=['.'])

# ============================== #

cpu = bld.env['DEST_CPU']
cpu_copy_path_map = {
    'x86': 'x86',
    'x86_64': 'x86_64',
    'arm': 'armeabi-v7a',
    'arm64': 'arm64-v8a',
    # Unsupported
    # 'armeabi-v7a': 'armeabi-v7a',
    # 'mips': 'mips',
    # 'mips64': 'mips64',
}
if cpu not in cpu_copy_path_map:
    bld.fatal("Unsupported Destination CPU: {}".format(cpu))

copy_path_platform = cpu_copy_path_map[cpu]

# =========== SINK =========== #

bld(features='cxx cxxshlib copy_binary',
    source=['sink/sink_jni.cpp'],
    target='sink_jni',
    install_path=None,
    copy_path='../sink/src/main/jniLibs/' + copy_path_platform,
    lib=['android'],
    use=['jutils', 'score_static'])

bld(features='cxx cxxshlib copy_binary',
    source=['sink/score_sink_version_jni.cpp'],
    target='score_sink_version_jni',
    install_path=None,
    copy_path='../sink/src/main/jniLibs/' + copy_path_platform,
    lib=['android'],
    use=['STEINWURF_VERSION'])

# =========== SOURCES =========== #

bld(features='cxx cxxshlib copy_binary',
    source=['source/manual_source_jni.cpp'],
    target='manual_source_jni',
    install_path=None,
    copy_path='../source/src/main/jniLibs/' + copy_path_platform,
    lib=['android'],
    use=['jutils', 'score_static'])

bld(features='cxx cxxshlib copy_binary',
    source=['source/auto_source_jni.cpp'],
    target='auto_source_jni',
    install_path=None,
    copy_path='../source/src/main/jniLibs/' + copy_path_platform,
    lib=['android'],
    use=['jutils', 'score_static'])

bld(features='cxx cxxshlib copy_binary',
    source=['source/score_source_version_jni.cpp'],
    target='score_source_version_jni',
    install_path=None,
    copy_path='../source/src/main/jniLibs/' + copy_path_platform,
    lib=['android'],
    use=['STEINWURF_VERSION'])
